// Generated by CoffeeScript 1.6.3
var DownScene, GameWorld, Map, g_resources, s_CloseNormal, s_CloseSelected, s_HelloWorld;

s_HelloWorld = 'res/HelloWorld.png';

s_CloseNormal = 'res/CloseNormal.png';

s_CloseSelected = 'res/CloseSelected.png';

g_resources = [
  {
    src: s_HelloWorld
  }, {
    src: s_CloseNormal
  }, {
    src: s_CloseSelected
  }
];

Map = (function() {
  function Map(layer) {
    var size;
    size = cc.Director.getInstance().getWinSize();
    this.sprite = cc.Sprite.create("res/HelloWorld.png");
    console.log("map pos: " + size.width + ", " + size.height);
    this.sprite.setPosition(cc.p(size.width / 2, size.height / 2));
    layer.addChild(this.sprite, 0);
  }

  Map.prototype.moveDelta = function(dx, dy) {
    var pos;
    pos = this.sprite.getPosition();
    return this.sprite.setPosition(cc.p(pos.x + dx, pos.y + dy));
  };

  return Map;

})();

GameWorld = cc.Layer.extend({
  isMouseDown: false,
  helloImg: null,
  helloLabel: null,
  circle: null,
  init: function() {
    this._super();
    this.touchStartX = 0;
    this.touchStartY = 0;
    this.map = new Map(this);
    this.setTouchEnabled(true);
    return true;
  },
  menuCloseCallback: function(sender) {
    return cc.Director.getInstance().end();
  },
  onTouchesBegan: function(touches, event) {
    if (touches) {
      this.isMouseDown = true;
      this.touchStartX = touches[0].getLocation().x;
      return this.touchStartY = touches[0].getLocation().y;
    }
  },
  onTouchesMoved: function(touches, event) {
    if (this.isMouseDown) {
      if (touches) {
        this.map.moveDelta(touches[0].getLocation().x - this.touchStartX, touches[0].getLocation().y - this.touchStartY);
        this.touchStartX = touches[0].getLocation().x;
        return this.touchStartY = touches[0].getLocation().y;
      }
    }
  },
  onTouchesEnded: function(touches, event) {
    return this.isMouseDown = false;
  },
  onTouchesCancelled: function(touches, event) {
    return console.log("onTouchesCancelled");
  }
});

DownScene = cc.Scene.extend({
  onEnter: function() {
    var layer;
    this._super();
    layer = new GameWorld();
    layer.init();
    return this.addChild(layer);
  }
});

//# sourceMappingURL=game.map
